### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by namalesamamira** [mjlogan/MauticInfoBipSmsBundle#5]
The installation documentation seems outdated or wrong or I am unable to install this.

- MauticInfoBipSmsBundle this folder does not exist. 
- After creating this folder in the plugins directory, and adding the plugin files there and clicking on "Install/Upgrade Plugins", I get a popup saying "0 plugins installed and 0 plugins updated".

____

Mautic 2.11.0

**Comment by namalesamamira** [comment]
It finally installed, with the chrome debugger open to prevent caching.

The documentation can still be reworded better. Will look into it soon

**Comment by namalesamamira** [comment]
The configuration process is also cryptic. There is no telling which keys go where because the fields in the config form are named differently from the ones from Infobip.

![screenshot from 2017-12-06 02-13-33](https://user-images.githubusercontent.com/1092294/33636075-b79a4f4c-da2b-11e7-8acc-7721d76d8571.png)

I cant get past here.

Whatever i put in produces no error, and when i go to the texts channel, I get an error about a missing config

![screenshot from 2017-12-06 02-20-16](https://user-images.githubusercontent.com/1092294/33636166-25e77ba0-da2c-11e7-8a85-dbb2949e59b6.png)

**Comment by sharique1988** [comment]
After uploading the plugin files run this command from console:-
sudo php PathToMauticInstallation/app/console cache:clear
Then Try to Install / Upgrade Plugins. You will see a new plugin appears there.

**Comment by vimalbahuguna** [comment]
Hi,
I installed Mautic 1.13.1. After clearing cache, I am able to see installed Infobip plugin. I configured user name and password and sending number. But in Setting->configuration->Text Message Settings->Select default transport to use  option, I am not able to select Infobib. As it is not appearing in list box. While Twilio is there. Please help. Thanks in advance
