### ISSUE TITLE
Can't create a message in mautic v2.12.1 

### ISSUE THREAD

**Issue by donmaciu** [mjlogan/MauticInfoBipSmsBundle#7]
I cannot create a text message. When I try, I see errors in my js console (Error 500) and in my logs I see sth like this: 

`[2018-02-12 13:36:11] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchIndexException: "Cannot read index "name" from object of type "Mautic\SmsBundle\Entity\Sms" because it doesn't implement \ArrayAccess." at /var/www/mautic/vendor/symfony/property-access/PropertyAccessor.php line 423 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchIndexException(code: 0): Cannot read index \"name\" from object of type \"Mautic\\SmsBundle\\Entity\\Sms\" because it doesn't implement \\ArrayAccess. at /var/www/mautic/vendor/symfony/property-access/PropertyAccessor.php:423)"} []`

**Comment by big89** [comment]
Hello, we had same issue. Any updates please let us know. Thanks.

**Comment by big89** [comment]
Any updates on this issue. please let us know what is the exact issue is this.

**Comment by big89** [comment]
Finally, we solved the issue and custom plugin with our own sms gateway working fine with Mautic 2.12.0 version.

**Comment by vimalbahuguna** [comment]
Hi,
I installed Mautic 1.13.1. After clearing cache, I am able to see installed Infobip plugin. I configured user name and password and sending number. But in Setting->configuration->Text Message Settings->Select default transport to use option, I am not able to select Infobip. As it is not appearing in list box. While Twilio is there. Please help. Thanks in advance
![image](https://user-images.githubusercontent.com/3713682/40951142-619da26e-6893-11e8-986d-5f3ab6f637c1.png)

**Comment by wakeu123** [comment]
To solve this problem please contact me via georgeswakeu21@gmail.com or by facebook via georges wakeu

**Comment by mjlogan** [comment]
No fixes/updates are currently being made by myself to the codebase. Contributions are welcome.
