### ISSUE TITLE
Mautic 2.13.1 Infobip configuration Problem

### ISSUE THREAD

**Issue by vimalbahuguna** [mjlogan/MauticInfoBipSmsBundle#8]
Hi,
I installed Mautic 1.13.1. After clearing cache, I am able to see installed Infobip plugin. I configured user name and password and sending number. But in Setting->configuration->Text Message Settings->Select default transport to use  option, I am not able to select Infobip. As it is not appearing in list box. While Twilio is there. Please help. Thanks in advance. Also identified some critical error log, on publishing Infobip plugin and creating new campaign after putting send text message action- not sure what is this-\[2018-06-05 08:00:46] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Process\Exception\InvalidArgumentException: "The key, 'sms.send_text_sms' is already used by another action. Please use a different key." at /home/silenf9z/public_html/mautic/mautic/app/bundles/CampaignBundle/Event/CampaignBuilderEvent.php line 224 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\InvalidArgumentException(code: 0): The key, 'sms.send_text_sms' is already used by another action. Please use a different key. at /home/silenf9z/public_html/mautic/mautic/app/bundles/CampaignBundle/Event/CampaignBuilderEvent.php:224)"} []  
![image](https://user-images.githubusercontent.com/3713682/40951178-872e3f8e-6893-11e8-87d5-41e339cd755e.png)

**Comment by big89** [comment]
Is this module working on Mautic latest version 2.13.1 ? I think its only tested upto 2.10.1

**Comment by vimalbahuguna** [comment]
With reference to https://github.com/mjlogan/MauticInfoBipSmsBundle/issues/7, it seems it is working upto v2.12.1

**Comment by big89** [comment]
The module available in this repository is not working for latest version of Mautic. We made it compatible for v2.12.1

You can contact us for further help at : bhagwansahane89@gmail.com

Thanks,
Logicmaker

**Comment by mjlogan** [comment]
@big89  You can submit a pull request, as I'm not currently able to implement the needed changes for newer versions.

**Comment by nicolabisio** [comment]
I'm also the same problem...after clearing cache deleting app/cache folder, I've installed and configured custom plugin, but no provider appear in Configuration > Text Message select option. 
I don't see any log file in my root folder in any case.
Any suggestion @big89 ?

**Comment by big89** [comment]
Lets connect over skype at bhagwan.sahane or email bhagwansahane89@gmail.com
We will try to help you in this regard.
Thanks !!!

**Comment by nicolabisio** [comment]
@big89 I've wrote you yesterday on skype, when you have a little time, could you help me?

**Comment by ravinayag** [comment]
I end up with the same problem, I'm running 2.15.1 with php 7.  Because of this my campaigns are not opening and getting internal server error 500.

could anyone know where these keys are stored in mautic ?

[2019-06-30 04:44:55] mautic.CRITICAL: Uncaught PHP Exception Mautic\CampaignBundle\Event\Exception\KeyAlreadyRegisteredException: "The key, 'sms.send_text_sms' is already used by another action. Please use a different key." at /var/www/html/mautic/app/bundles/CampaignBundle/Event/CampaignBuilderEvent.php line 227 {"exception":"[object] (Mautic\\CampaignBundle\\Event\\Exception\\KeyAlreadyRegisteredException(code: 0): The key, 'sms.send_text_sms' is already used by another action. Please use a different key. at /var/www/html/mautic/app/bundles/CampaignBundle/Event/CampaignBuilderEvent.php:227)"} []

**Comment by bijupanicker** [comment]
@big89 
We are facing the same issue. Could you please help resolve the issue or share the fix done..

**Comment by ravinayag** [comment]
If you facing issues as i had,  then the workaround is to go settings/plugins and click infobip plugin and  select NO on the published

**Comment by big89** [comment]
Hello,

Please connect over Skype at : bhagwan.sahane

So, we can discuss in detail.


Thanks & Regards,

Bhagwan Sahane
Logicmaker Softwares
www.logicmaker.in

**Comment by mjlogan** [comment]
No fixes/updates are currently being made by myself to the codebase. Contributions are welcome.
