### ISSUE TITLE
getting error in mautic 3.2

### ISSUE THREAD

**Issue by namratasaun** [mjlogan/MauticInfoBipSmsBundle#9]
Class "Mautic\CoreBundle\EventListener\CommonSubscriber" not found while loading "MauticPlugin\MauticInfoBipSmsBundle\EventListener\CampaignSubscriber". 
This is the error I am facing

**Comment by mjlogan** [comment]
The codebase is no longer being updated for Mautic versions later than 2.8.2.  No new fixes will be made by myself, but contributions could be evaluated/integrated to the code.
